version: "2"
services:
    web:
        build:          "./web"
        volumes:        [ "./web:/var/www/html" ]
        ports:          [ "10000:80" ]
        links:          [ "db" ]
        depends_on:     [ "db" ]

    db:
        image:          "mysql:5.6.27"
        ports:          [ "10001:3306" ]
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_HOST=db
            - MYSQL_DATABASE=test
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - ./db/script:/script
            - ./db/log:/var/log/mysql
            - ./db/mysql:/var/lib/mysql

        command: "/script/permissions.sh"


    phpmyadmin:
        image:          "corbinu/docker-phpmyadmin"
        ports:          [ "10002:80" ]
        links:          [ "db" ]
        depends_on:     [ "db" ]
        environment:
            MYSQL_USERNAME:         "root"
            MYSQL_ROOT_PASSWORD:    "test"
