version: "2"
services:
    web:
        build:
            context:        "."
            dockerfile:     "web.df"
        volumes:        [ "./html:/var/www/html" ]
        ports:          [ "80:80" ]
        links:          [ "db" ]

    db-data:
        image:          "busybox"
        volumes:        [ "/var/lib/mysql" ]

    db:
        image:          "mariadb"
        ports:          [ "3306:3306" ]
        volumes_from:   [ "db-data" ]
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
